             spring.application.name=ai-log-monitor
spring.output.ansi.enabled=always

# -----------------------------
# PostgreSQL Database
# -----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_log_monitor
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------
# Hibernate & JPA
# -----------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

# -----------------------------
# AI Providers (Environment Variables)
# -----------------------------

# OpenRouter (Chat)
openrouter.api.key=${OPENROUTER_API_KEY:}
openrouter.url=https://openrouter.ai/api/v1/chat/completions

# Ollama Chat
ollama.chat.url=http://localhost:11434/api/generate
ollama.chat.model=qwen2.5:3b

# Ollama Embedding
ollama.url=http://localhost:11434/api/embeddings
ollama.embedding.model=nomic-embed-text

# -----------------------------
# Spring Mail SMTP (Environment Variables)
# -----------------------------
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:hatiiceeenuurr@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:vhuhxpdvbepgrhbt}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# -----------------------------
# Application & Retention
# -----------------------------
log.file.path=logs/application.log
simulation.interval=30000
# Monitor Scheduler Interval in ms
monitor.interval=900000
retention.days=14

# -----------------------------
# Notifications & RAG Search
# -----------------------------
notification.enabled=true
slack.webhook.url=${SLACK_WEBHOOK_URL:}
rag.similarity-threshold=70
rag.top-k=5