spring.application.name=ai-log-monitor

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_log_monitor
spring.datasource.username=postgres
spring.datasource.password=123456

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

# -----------------------------
# AI Providers
# -----------------------------

# OpenRouter (Chat)
openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.url=https://openrouter.ai/api/v1/chat/completions

# Ollama Chat
ollama.chat.url=http://localhost:11434/api/generate
ollama.chat.model=qwen2.5:3b

# Ollama Embedding
ollama.url=http://localhost:11434/api/embeddings
ollama.embedding.model=nomic-embed-text

# -----------------------------
# Application
# -----------------------------

log.file.path=logs/application.log
simulation.interval=30000
monitor.interval=3600000